# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Expense.destroy_all
ExpenseMember.destroy_all
Friend.destroy_all
Comment.destroy_all

User.create(username: "Demo User", email: "demo_user@gmail.com", password: "password")
User.create(username: "John Cigale", email: "jcigale@appacademy.io", password: "expirednuts")
User.create(username: "Kin Ka Tse", email: "ktse@appacademy.io", password: "bubbletea")
User.create(username: "Jim Nardi", email: "jnardi@appacademy.io", password: "gilfoyle")
User.create(username: "Kyle Ginzburg", email: "kginzburg@appacademy.io", password: "opcomputer")
User.create(username: "Amin Babar", email: "ababar@appacademy.io", password: "olympicswinner")
User.create(username: "Chris Moore", email: "cmoore@gmail.com", password: "ratatouille")
User.create(username: "Derek Lee", email: "dlee@gmail.com", password: "teamsolomid")
User.create(username: "Dominic Swaby", email: "dswaby@gmail.com", password: "fortune500")
User.create(username: "Harry Israel", email: "hisrael@gmail.com", password: "cantkeepmedown")
User.create(username: "Herman He", email: "hhe@gmail.com", password: "difficultquestions")
User.create(username: "Janice Shih", email: "jshih@gmail.com", password: "metabuyout")
User.create(username: "Jackson Dooley", email: "jdooley@gmail.com", password: "questgiver")
User.create(username: "Jacob Benowitz", email: "jbenowitz@gmail.com", password: "nostradamus")
User.create(username: "Joe Delaney", email: "jdelaney@gmail.com", password: "heismyboss")
User.create(username: "Kevin Tung", email: "ktung@gmail.com", password: "newcodinglanguage")
User.create(username: "Nicholas Angleton", email: "nangleton@gmail.com", password: "coldbrewcoder")
User.create(username: "Johnny Mei", email: "jmei@gmail.com", password: "sleepingpirate")
User.create(username: "Peter Kim", email: "pkim@gmail.com", password: "rockybalboa")
User.create(username: "Sean O'Dea", email: "sodea@gmail.com", password: "kingofmountain")
User.create(username: "Spencer Lee", email: "slee@gmail.com", password: "appliedmathmajor")
User.create(username: "Will Corona", email: "wcorona@gmail.com", password: "enjoyerenjoyer")

Expense.create(owner_id: 6, amount: 36.00, description: "Lunch", split_option: "equally")
Expense.create(owner_id: 4, amount: 10.00, description: "Coffee", split_option: "equally")
Expense.create(owner_id: 1, amount: 24.00, description: "Churros", split_option: "equally")
Expense.create(owner_id: 12, amount: 120.00, description: "Groceries", split_option: "equally")
Expense.create(owner_id: 20, amount: 375.00, description: "Gym Membership", split_option: "equally")
Expense.create(owner_id: 2, amount: 15.00, description: "Snacks", split_option: "equally")
Expense.create(owner_id: 17, amount: 48.00, description: "Pizza", split_option: "equally")
Expense.create(owner_id: 15, amount: 55.00, description: "Movie Night", split_option: "equally")
Expense.create(owner_id: 21, amount: 28.00, description: "Ice Cream", split_option: "equally")
Expense.create(owner_id: 14, amount: 60.00, description: "BBQ", split_option: "equally")

ExpenseMember.create(user_id: 6, expense_id: 1, balance: 12.00)
ExpenseMember.create(user_id: 5, expense_id: 1, balance: 12.00)
ExpenseMember.create(user_id: 4, expense_id: 1, balance: 12.00)
ExpenseMember.create(user_id: 4, expense_id: 2, balance: 5.00)
ExpenseMember.create(user_id: 1, expense_id: 2, balance: 5.00)
ExpenseMember.create(user_id: 1, expense_id: 3, balance: 6.00)
ExpenseMember.create(user_id: 2, expense_id: 3, balance: 6.00)
ExpenseMember.create(user_id: 3, expense_id: 3, balance: 6.00)
ExpenseMember.create(user_id: 6, expense_id: 3, balance: 6.00)
ExpenseMember.create(user_id: 12, expense_id: 4, balance: 40.00)
ExpenseMember.create(user_id: 10, expense_id: 4, balance: 40.00)
ExpenseMember.create(user_id: 22, expense_id: 4, balance: 40.00)
ExpenseMember.create(user_id: 20, expense_id: 5, balance: 75.00)
ExpenseMember.create(user_id: 1, expense_id: 5, balance: 75.00)
ExpenseMember.create(user_id: 11, expense_id: 5, balance: 75.00)
ExpenseMember.create(user_id: 7, expense_id: 5, balance: 75.00)
ExpenseMember.create(user_id: 9, expense_id: 5, balance: 75.00)
ExpenseMember.create(user_id: 2, expense_id: 6, balance: 7.50)
ExpenseMember.create(user_id: 1, expense_id: 6, balance: 7.50)
ExpenseMember.create(user_id: 17, expense_id: 7, balance: 8.00)
ExpenseMember.create(user_id: 1, expense_id: 7, balance: 8.00)
ExpenseMember.create(user_id: 8, expense_id: 7, balance: 8.00)
ExpenseMember.create(user_id: 19, expense_id: 7, balance: 8.00)
ExpenseMember.create(user_id: 13, expense_id: 7, balance: 8.00)
ExpenseMember.create(user_id: 18, expense_id: 7, balance: 8.00)
ExpenseMember.create(user_id: 15, expense_id: 8, balance: 27.50)
ExpenseMember.create(user_id: 14, expense_id: 8, balance: 27.50)
ExpenseMember.create(user_id: 21, expense_id: 9, balance: 14.00)
ExpenseMember.create(user_id: 13, expense_id: 9, balance: 14.00)
ExpenseMember.create(user_id: 14, expense_id: 10, balance: 20.00)
ExpenseMember.create(user_id: 1, expense_id: 10, balance: 20.00)
ExpenseMember.create(user_id: 17, expense_id: 10, balance: 20.00)

Friend.create(user_id: 6, friend_id: 5)
Friend.create(user_id: 5, friend_id: 6)
Friend.create(user_id: 6, friend_id: 4)
Friend.create(user_id: 4, friend_id: 6)
Friend.create(user_id: 4, friend_id: 1)
Friend.create(user_id: 1, friend_id: 4)
Friend.create(user_id: 1, friend_id: 2)
Friend.create(user_id: 2, friend_id: 1)
Friend.create(user_id: 1, friend_id: 3)
Friend.create(user_id: 3, friend_id: 1)
Friend.create(user_id: 1, friend_id: 6)
Friend.create(user_id: 6, friend_id: 1)
Friend.create(user_id: 12, friend_id: 10)
Friend.create(user_id: 10, friend_id: 12)
Friend.create(user_id: 12, friend_id: 22)
Friend.create(user_id: 22, friend_id: 12)
Friend.create(user_id: 20, friend_id: 1)
Friend.create(user_id: 1, friend_id: 20)
Friend.create(user_id: 20, friend_id: 11)
Friend.create(user_id: 11, friend_id: 20)
Friend.create(user_id: 20, friend_id: 7)
Friend.create(user_id: 7, friend_id: 20)
Friend.create(user_id: 20, friend_id: 9)
Friend.create(user_id: 9, friend_id: 20)
Friend.create(user_id: 2, friend_id: 1)
Friend.create(user_id: 1, friend_id: 2)
Friend.create(user_id: 17, friend_id: 1)
Friend.create(user_id: 1, friend_id: 17)
Friend.create(user_id: 17, friend_id: 8)
Friend.create(user_id: 8, friend_id: 17)
Friend.create(user_id: 17, friend_id: 19)
Friend.create(user_id: 19, friend_id: 17)
Friend.create(user_id: 17, friend_id: 13)
Friend.create(user_id: 13, friend_id: 17)
Friend.create(user_id: 17, friend_id: 18)
Friend.create(user_id: 18, friend_id: 17)
Friend.create(user_id: 15, friend_id: 14)
Friend.create(user_id: 14, friend_id: 15)
Friend.create(user_id: 21, friend_id: 13)
Friend.create(user_id: 13, friend_id: 21)
Friend.create(user_id: 14, friend_id: 1)
Friend.create(user_id: 1, friend_id: 14)
Friend.create(user_id: 14, friend_id: 17)
Friend.create(user_id: 17, friend_id: 14)

Comment.create(author_id: 5, expense_id: 1, body: "Thanks for lunch :)")
Comment.create(author_id: 1, expense_id: 2, body: "Coffee was great")
Comment.create(author_id: 3, expense_id: 3, body: "These churros were kind of stale")
Comment.create(author_id: 10, expense_id: 4, body: "I really appreciate your kindness")
Comment.create(author_id: 11, expense_id: 5, body: "I got you next time")
Comment.create(author_id: 2, expense_id: 6, body: "Where's my money :(")
Comment.create(author_id: 8, expense_id: 7, body: "I think I got food poisoning from the pizza")
Comment.create(author_id: 15, expense_id: 8, body: "To our last days at App Academy :D")
Comment.create(author_id: 21, expense_id: 9, body: "I really appreciate your leadership")
Comment.create(author_id: 17, expense_id: 10, body: "I would love to go back there again")